spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/forezp/SpringcloudConfig/
          search-paths: respo
          username: your username
          password: your password

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8889/eureka/

